GaithAlQuraniProject/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GaithAlQuraniProject.Data;
using GaithAlQuraniProject.Models;
using Plugin.Messaging;

namespace GaithAlQuraniProject.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactUsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ContactUs
        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactUs.ToListAsync());
        }

        // GET: ContactUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // GET: ContactUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( ContactUs contactUs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactUs);
                await _context.SaveChangesAsync();
                //Email();
                return RedirectToAction(nameof(Index));
            }
            return View(contactUs);
        }


        // GET: ContactUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs.FindAsync(id);
            if (contactUs == null)
            {
                return NotFound();
            }
            return View(contactUs);
        }

        // POST: ContactUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Subject,Email,Message")] ContactUs contactUs)
        {
            if (id != contactUs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactUs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactUsExists(contactUs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactUs);
        }

        // GET: ContactUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // POST: ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactUs = await _context.ContactUs.FindAsync(id);
            _context.ContactUs.Remove(contactUs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactUsExists(int id)
        {
            return _context.ContactUs.Any(e => e.Id == id);
        }
    }
}

GaithAlQuraniProject/Controllers/NewRegisteredStudentsController.cs
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System;
using System.Security.Cryptography;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GaithAlQuraniProject.Data;
using GaithAlQuraniProject.Models;

namespace GaithAlQuraniProject.Controllers
{
    public class NewRegisteredStudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NewRegisteredStudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NewRegisteredStudents
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewRegisteredStudent.ToListAsync());
        }

        // GET: NewRegisteredStudents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newRegisteredStudent = await _context.NewRegisteredStudent
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newRegisteredStudent == null)
            {
                return NotFound();
            }

            return View(newRegisteredStudent);
        }

        // GET: NewRegisteredStudents/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: NewRegisteredStudents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewRegisteredStudent newRegisteredStudent)
        {
           
            if (ModelState.IsValid)
            {
                var checkUserName = _context.NewRegisteredStudent.Where(x => x.UserName == newRegisteredStudent.UserName).SingleOrDefault();
                if(checkUserName == null)
                {

                    newRegisteredStudent.Password = HashPassword(newRegisteredStudent.Password);//will assign the hash to the password field
                    _context.Add(newRegisteredStudent);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(StudentLogin));//after seccuss registration pop up message
                }
                return View(newRegisteredStudent); /*must an error be showed if the username exists*/
            }
            return View(newRegisteredStudent);
        }

     
        // GET: NewRegisteredStudents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newRegisteredStudent = await _context.NewRegisteredStudent.FindAsync(id);
            if (newRegisteredStudent == null)
            {
                return NotFound();
            }
            return View(newRegisteredStudent);
        }

        // POST: NewRegisteredStudents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NewRegisteredStudent newRegisteredStudent)
        {
            if (id != newRegisteredStudent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newRegisteredStudent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewRegisteredStudentExists(newRegisteredStudent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newRegisteredStudent);
        }

        // GET: NewRegisteredStudents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newRegisteredStudent = await _context.NewRegisteredStudent
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newRegisteredStudent == null)
            {
                return NotFound();
            }

            return View(newRegisteredStudent);
        }

        // POST: NewRegisteredStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newRegisteredStudent = await _context.NewRegisteredStudent.FindAsync(id);
            _context.NewRegisteredStudent.Remove(newRegisteredStudent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewRegisteredStudentExists(int id)
        {
            return _context.NewRegisteredStudent.Any(e => e.Id == id);
        }


        public IActionResult StudentLogin()
        {
            return View();
        }

        
        public IActionResult StudentEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newRegisteredStudent =  _context.NewRegisteredStudent.Find(id);
            if (newRegisteredStudent == null)
            {
                return NotFound();
            }
            return View(newRegisteredStudent);
        }

        [HttpPost]
        public IActionResult StudentIndex(StudentLogin studentLogin)
        {
            if (ModelState.IsValid)
            {
                    var result = _context.NewRegisteredStudent.Where(x => x.UserName == studentLogin.UserName).Single(); //if null ? or does not exist
                    if (VerifyPassword(result.Password, studentLogin.Password))
                    {
                        return View("StudentIndex", result);
                    }
                             
                return View("StudentLogin", studentLogin);
            }
            return View("StudentLogin", studentLogin);
            
            //while registration make sure the name does not exist


            //must do username 
            //check in the internet how to implement login
            //send the new password to verifyPass 
            //if true then check the username

            
            // return View(await _context.NewRegisteredStudent.ToListAsync());

        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StudentEdit(int id, NewRegisteredStudent newRegisteredStudent)
        {
            if (id != newRegisteredStudent.Id)
            {
                return NotFound();
            }

           if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newRegisteredStudent);
                    await _context.SaveChangesAsync();
                }
               catch (DbUpdateConcurrencyException)
                {
                    if (!NewRegisteredStudentExists(newRegisteredStudent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("StudentIndex", newRegisteredStudent);       
            }
            return View(newRegisteredStudent); 
        }

        public async Task<IActionResult> ChooseFriend(string SearchBy, string search, int id)
        {
            var student = _context.NewRegisteredStudent.Where(s => s.Id == id).SingleOrDefault();
            ViewData["student"] = student;
            if (SearchBy == "Rewayah")
            {
                return View(await _context.NewRegisteredStudent.Where(x => x.Rewayah.StartsWith(search) || search == null).ToListAsync());
            }
            else if (SearchBy == "Country")
            {
                return View(await _context.NewRegisteredStudent.Where(x => x.Country.StartsWith(search) || search == null).ToListAsync());
            }
            else
            {
                return View(await _context.NewRegisteredStudent.Where(x => x.CallingProgram.StartsWith(search) || search == null).ToListAsync());

            }
            
        }

        public IActionResult addFriend(int id, int idF)
        {
            try
            {
                var student = _context.NewRegisteredStudent.Where(s => s.Id == id).SingleOrDefault();
                var friend = _context.NewRegisteredStudent.Where(s => s.Id == idF).SingleOrDefault();

                student.FriendName = friend.Name;//time
                student.FriendStatusT = "true";//check later
                _context.SaveChanges();
                friend.FriendStatusT = "true";//time
                friend.FriendName = student.Name;//time
                _context.SaveChanges();
                return View("StudentIndex", student);
            }
            catch
            {
                var student = _context.NewRegisteredStudent.Where(s => s.Id == id).SingleOrDefault();
                return View("ChooseFriend", student);
            }

        }

        private string HashPassword(string password, byte[] salt = null, bool needsOnlyHash = false)
        {
            if (salt == null || salt.Length != 16)
            {

GaithAlQuraniProject/Views/Shared/_Layout.cshtml
@using System.Globalization;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title> @ViewData["Title"] - غيث القرآني</title>
    <meta content="" name="description">
    <meta content="" name="keywords">


    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon"> <!--change -->

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
          integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/vendor/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <link href="~/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
        <!-- Essential Studio for JavaScript  theme reference -->
        <link rel="stylesheet" href="//cdn.syncfusion.com/17.1.0.38/js/web/flat-azure/ej.web.all.min.css" />
</head>

<body>
    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
        <div class="container d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <!--  <a href="https://mobile.twitter.com/gaith_quraany?lang=ar" target="_blank">

                        <i class="fab fa-twitter fa-2x " style="color: #2eced9;
                font-size: 16px;
                background-color: #fff; border-radius: 5px"></i>
                        </a> <!--fix the twitter icon in mobile devices-->
                <!--insert the link by db-->
                <a href="https://mobile.twitter.com/gaith_quraany?lang=ar" target="_blank">
                    <i class="fab fa-twitter fa-2x " style="color: #fff"></i>
                </a>
            </div>
            <div class="d-flex align-items-center">
                @DateTime.UtcNow.ToString(" dddd, yyyy - MMMM - dd ", new CultureInfo("ar-AE"))  <i class="icofont-clock-time m-2"></i>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center ">

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <!--  <li><a href="#departments">Departments</a></li>-->
@*                    <li class="drop-down"><a href="">Drop Down</a>
                      <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="drop-down"><a href="#">Deep Drop Down</a>
                          <ul>
                            <li><a href="#">Deep Drop Down 1</a></li>
                            <li><a href="#">Deep Drop Down 2</a></li>
                            <li><a href="#">Deep Drop Down 3</a></li>
                            <li><a href="#">Deep Drop Down 4</a></li>
                            <li><a href="#">Deep Drop Down 5</a></li>
                          </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                      </ul>
                    </li> *@
                    <partial name="~/Views/Shared/_LoginPartial.cshtml" />
                    <li><a id="#Home" asp-controller="ContactUs" asp-action="Create">التواصل</a></li>
                    <li class="drop-down"><a href="">الخدمات</a>
                      <ul>
                        <li><a asp-controller="NewRegisteredStudents" asp-action="Create">تسجيل في البرنامج</a></li>
                      </ul>
                    </li>  @* fix the active tab *@
                    <li><a href="/adminPanel/Home">لوحة التحكم</a></li>
                    <li><a id="#about" asp-controller="Home" asp-action="About">من نحن</a></li>
                    <li class="active"><a id="#Home" asp-controller="Home" asp-action="Index">الرئيسية</a></li> <!--Reverse the menu-->

                </ul>
            </nav><!-- .nav-menu -->
            <!-- <a href="index.html" class="logo " style="margin-left: auto !important"><img src="~/img/logo.png" alt=""></a>-->
            <!-- Uncomment below if you prefer to use an image logo -->
            <h1 class="logo " style="margin-left: auto !important">
                <a asp-controller="Home" asp-action="Index">غيث القرآني<i class="fas fa-cloud  mb-2 mr-2" style="color: #2eced9"></i></a>
            </h1>

        </div>
       
    </header><!-- End Header -->
    <!--use the partial to add the showcase here and put the script only in the home view-->
<main role="main" class="pb-1">
    @RenderBody()
</main>
    <!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span> Gaith Al-Gurani</span></strong>. All Rights Reserved 
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medicio-free-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/" style="color: #2eced9">BootstrapMade</a><br />
                Developed by <span style="color: #2eced9">Safa Ismat</span>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

          


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>

    <!-- Vendor JS Files -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/vendor/counterup/counterup.min.js"></script>
    <script src="~/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/vendor/venobox/venobox.min.js"></script>
    <script src="~/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    <!-- Essential Studio for JavaScript  script references -->
    <script src="//cdn.syncfusion.com/js/assets/external/jsrender.min.js"></script>
    <script src="//cdn.syncfusion.com/17.1.0.38/js/web/ej.web.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

<ej-script-manager></ej-script-manager>